name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.1"
          - ruby-head
          - truffleruby-head
        task:
          - internal_investigation
          - spec
    name: "Ruby ${{ matrix.ruby }}: ${{ matrix.task }}"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      - run: bundle exec rake ${{ matrix.task }}
